const fs = require('fs');

const langs = [
    { file: 'ru.json', data: { badge: "Отзывы", title: "Что говорят наши гости", desc: "Настоящие истории семей и туристических групп, выбравших комфорт Heaven Feel.", items: [{ name: "Семья Ивановых (7 человек)", text: "«Идеальное место для нашей огромной семьи. Гораздо удобнее и дешевле, чем снимать 3 разных номера в отеле!»" }, { name: "Туристическая группа из Казани", text: "«Прекрасная кухня и огромный зал, где мы все могли собраться вечером. Настоящее узбекское гостеприимство.»" }, { name: "Семья Смирновых (5 человек)", text: "«Дети были в восторге от пространства. Очень чисто, безопасно и уютно. Как будто приехали домой.»" }] } },
    { file: 'uz.json', data: { badge: "Fikrlar", title: "Mehmonlarimiz nima deydi", desc: "Heaven Feel qulayligini tanlagan oilalar va turistlarning haqiqiy hikoyalari.", items: [{ name: "Olimovlar oilasi (7 kishi)", text: "«Katta oilamiz uchun ajoyib joy. Mehmonxonadan 3 ta alohida xona olgandan ko'ra ancha qulay va arzon!»" }, { name: "Qozog'istonlik turistlar guruhi", text: "«Kechqurun hammamiz yig'ilishimiz uchun katta zal va ajoyib oshxona. Haqiqiy o'zbek mehmondo'stligi.»" }, { name: "Saidovlar oilasi (5 kishi)", text: "«Bolalarga juda yoqdi. Juda toza, xavfsiz shinam. Huddi o'z uyimizdagidek.»" }] } },
    { file: 'en.json', data: { badge: "Reviews", title: "What Our Guests Say", desc: "Real stories from families and tourist groups who chose the comfort of Heaven Feel.", items: [{ name: "The Smiths (7 people)", text: "«Perfect place for our huge family. Much more convenient and cheaper than booking 3 different hotel rooms!»" }, { name: "Tourist Group from Germany", text: "«Beautiful kitchen and a highly spacious hall where we could all gather in the evening. True hospitality.»" }, { name: "The Johnsons (5 people)", text: "«The kids loved the space. Very clean, safe, and cozy. Felt just like home.»" }] } },
    { file: 'kk.json', data: { badge: "Пікірлер", title: "Қонақтарымыз не дейді", desc: "Heaven Feel жайлылығын таңдаған отбасылар мен туристік топтардың нақты хикаялары.", items: [{ name: "Омаровтар отбасы (7 адам)", text: "«Үлкен отбасымыз үшін тамаша орын. Қонақүйде 3 бөлек бөлме алғаннан әлдеқайда ыңғайлы әрі арзан!»" }, { name: "Түркиядан келген туристер тобы", text: "«Кешке бәріміз жиналатын үлкен зал мен тамаша асүй. Нағыз қонақжайлылық.»" }, { name: "Серіковтер отбасы (5 адам)", text: "«Балаларға қатты ұнады. Өте таза, қауіпсіз әрі жайлы. Өз үйіміздегідей.»" }] } },
    { file: 'ky.json', data: { badge: "Пикирлер", title: "Конокторубуз эмне дешет", desc: "Heaven Feel ыңгайлуулугун тандаган үй-бүлөлөр жана туристтик топтордун чыныгы окуялары.", items: [{ name: "Оморовдор үй-бүлөсү (7 адам)", text: "«Чоң үй-бүлөбүз үчүн эң сонун жер. Мейманканадан 3 бөлөк бөлмө алгандан көрө алда канча ыңгайлуу жана арзан!»" }, { name: "Россиядан келген туристтер тобу", text: "«Кечинде баарыбыз чогула турган чоң зал жана сонун ашкана. Чыныгы меймандостук.»" }, { name: "Садыковдор үй-бүлөсү (5 адам)", text: "«Балдарга абдан жакты. Абдан таза, коопсуз жана жайлуу. Өз үйүбүздөгүдөй сезилди.»" }] } },
    { file: 'tr.json', data: { badge: "Yorumlar", title: "Misafirlerimiz Ne Diyor", desc: "Heaven Feel rahatlığını seçen aileler ve turist gruplarının gerçek hikayeleri.", items: [{ name: "Öztürk Ailesi (7 kişi)", text: "«Büyük ailemiz için mükemmel bir yer. Otelde 3 ayrı oda tutmaktan çok daha rahat ve ucuz!»" }, { name: "Avrupa'dan Turist Grubu", text: "«Akşam hepimizin toplanabileceği büyük bir salon ve harika bir mutfak. Gerçek misafirperverlik.»" }, { name: "Yılmaz Ailesi (5 kişi)", text: "«Çocuklar çok sevdi. Çok temiz, güvenli ve rahat. Tıpkı kendi evimizdeki gibi.»" }] } },
    { file: 'az.json', data: { badge: "Rəylər", title: "Qonaqlarımız Nə Deyir", desc: "Heaven Feel rahatlığını seçən ailələr və turist qruplarının gerçək hekayələri.", items: [{ name: "Əliyevlər ailəsi (7 nəfər)", text: "«Böyük ailəmiz üçün mükəmməl yer. Oteldə 3 ayrı otaq tutmaqdan qat-qat rahat və ucuzdur!»" }, { name: "MDB-dən gələn turist qrupu", text: "«Axşam hamımızın toplana biləcəyi böyük zal və gözəl mətbəx. Əsl qonaqpərvərlik.»" }, { name: "Həsənovlar ailəsi (5 nəfər)", text: "«Uşaqlar çox bəyəndi. Çox təmiz, təhlükəsiz və rahat. Eynilə öz evimizdəki kimi.»" }] } }
];

for (const lang of langs) {
    const path = `./messages/${lang.file}`;
    if (fs.existsSync(path)) {
        const json = JSON.parse(fs.readFileSync(path, 'utf8'));
        delete json.feedback; // Remove old feedback
        json.reviews = lang.data; // Inject new reviews
        fs.writeFileSync(path, JSON.stringify(json, null, 2));
    }
}
console.log("Injected static reviews successfully.");
